-- -----------------------------------------------------
-- Table User
-- -----------------------------------------------------
CREATE TABLE User_ (
  iduser INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(45) NULL,
  username VARCHAR(45) NULL,
  password VARCHAR(45) NULL,
  image VARCHAR(200) NULL,
  PRIMARY KEY (iduser));

-- -----------------------------------------------------
-- Table Friend
-- -----------------------------------------------------
CREATE TABLE Friend (
  idfriend INTEGER GENERATED BY DEFAULT AS IDENTITY,
  iduser INT,
  idfriend1 INT,
  PRIMARY KEY (idfriend),
  CONSTRAINT fk_Amigo_Usuario
  FOREIGN KEY (iduser) 
  REFERENCES User_ (iduser),
  CONSTRAINT fk_Friend_User1
  FOREIGN KEY (idfriend1) REFERENCES User_ (iduser));


-- -----------------------------------------------------
-- Table Publication
-- -----------------------------------------------------
CREATE TABLE Publication (
  idpublication INTEGER GENERATED BY DEFAULT AS IDENTITY,
  text VARCHAR(45) NULL,
  iduser INT NOT NULL,
  image VARCHAR(200) NOT NULL,
  PRIMARY KEY (idpublication),
  CONSTRAINT fk_Publication_User1
    FOREIGN KEY (iduser)
    REFERENCES User_ (iduser));


-- -----------------------------------------------------
-- Table Tags
-- -----------------------------------------------------
CREATE TABLE Tags (
  idtags INTEGER GENERATED BY DEFAULT AS IDENTITY,
  tag VARCHAR(45) NULL,
  idpublication INT NOT NULL,
  PRIMARY KEY (idtags),
  CONSTRAINT fk_Tags_Publication1
    FOREIGN KEY (idpublication)
    REFERENCES Publication (idpublication));


-- -----------------------------------------------------
-- Table Message
-- -----------------------------------------------------
CREATE TABLE Message (
  idmessage INTEGER GENERATED BY DEFAULT AS IDENTITY,
  message VARCHAR(45) NULL,
  iduser1 INT NOT NULL,
  iduser2 INT NOT NULL,
  PRIMARY KEY (idmessage),
  CONSTRAINT fk_Message_User1
    FOREIGN KEY (iduser1)
    REFERENCES User_ (iduser),
  CONSTRAINT fk_Message_User2
    FOREIGN KEY (iduser2)
    REFERENCES User_ (iduser));


-- -----------------------------------------------------
-- Table Friend_Request
-- -----------------------------------------------------
CREATE TABLE Friend_Request (
  idrequest INTEGER GENERATED BY DEFAULT AS IDENTITY,
  iduser1 INT NOT NULL,
  iduser2 INT NOT NULL,
  PRIMARY KEY (idrequest),
  CONSTRAINT fk_Friend_Request_User1
    FOREIGN KEY (iduser1)
    REFERENCES User_ (iduser),
  CONSTRAINT fk_Friend_Request_User2
    FOREIGN KEY (iduser2)
    REFERENCES User_ (iduser));

-- -----------------------------------------------------
-- Procedure New User
-- -----------------------------------------------------
CREATE OR REPLACE PROCEDURE insertar_user(name in varchar, username_ in varchar,
password in varchar, image in varchar)
IS
existe number;
BEGIN
    existe:=0;
    SELECT Count(*) into existe 
    FROM User_
    WHERE username = username_;
    
    if existe = 0 then
        insert into User_(name,username, password, image) values(name, username_, password, image);
        dbms_output.put_line('Usuario registrado con exito: ' || username_);
    else
        existe := -1;
        dbms_output.put_line('No registrado error: ' || existe);
    end if;
END;

-- -----------------------------------------------------
-- Procedure Login
-- -----------------------------------------------------
CREATE OR REPLACE PROCEDURE Login(
        usu in User_.username%TYPE,
        pass in User_.password%TYPE)
    AS
        c SYS_REFCURSOR;
    BEGIN
        OPEN c for
        select * from User_ u where (u.username=usu and u.password=pass);
        dbms_sql.return_result(c);
    END;

COMMIT;
