DROP TABLE Prueba1;

CREATE TABLE Prueba1 
(
    idPrueba1 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(20),
    apellido VARCHAR(20)
);

INSERT INTO Prueba1(nombre,apellido) VALUES('Nombre','Prueba');
SELECT * FROM Prueba1
WHERE nombre = 'Diego';
select * from v$instance