-- -----------------------------------------------------
-- Table User
-- -----------------------------------------------------
CREATE TABLE User_ (
  iduser INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(45) NULL,
  username VARCHAR(45) NULL,
  password VARCHAR(45) NULL,
  image VARCHAR(200) NULL,
  PRIMARY KEY (iduser));

-- -----------------------------------------------------
-- Table Friend
-- -----------------------------------------------------
CREATE TABLE Friend (
  idfriend INTEGER GENERATED BY DEFAULT AS IDENTITY,
  iduser INT,
  idfriend1 INT,
  PRIMARY KEY (idfriend),
  CONSTRAINT fk_Amigo_Usuario
  FOREIGN KEY (iduser) 
  REFERENCES User_ (iduser),
  CONSTRAINT fk_Friend_User1
  FOREIGN KEY (idfriend1) REFERENCES User_ (iduser));


-- -----------------------------------------------------
-- Table Publication
-- -----------------------------------------------------
CREATE TABLE Publication (
  idpublication INTEGER GENERATED BY DEFAULT AS IDENTITY,
  text VARCHAR(45) NULL,
  iduser INT NOT NULL,
  image VARCHAR(200) NOT NULL,
  PRIMARY KEY (idpublication),
  CONSTRAINT fk_Publication_User1
    FOREIGN KEY (iduser)
    REFERENCES User_ (iduser));


-- -----------------------------------------------------
-- Table Tags
-- -----------------------------------------------------
CREATE TABLE Tags (
  idtags INTEGER GENERATED BY DEFAULT AS IDENTITY,
  tag VARCHAR(45) NULL,
  idpublication INT NOT NULL,
  PRIMARY KEY (idtags),
  CONSTRAINT fk_Tags_Publication1
    FOREIGN KEY (idpublication)
    REFERENCES Publication (idpublication));


-- -----------------------------------------------------
-- Table Message
-- -----------------------------------------------------
CREATE TABLE Message (
  idmessage INTEGER GENERATED BY DEFAULT AS IDENTITY,
  message VARCHAR(45) NULL,
  iduser1 INT NOT NULL,
  iduser2 INT NOT NULL,
  PRIMARY KEY (idmessage),
  CONSTRAINT fk_Message_User1
    FOREIGN KEY (iduser1)
    REFERENCES User_ (iduser),
  CONSTRAINT fk_Message_User2
    FOREIGN KEY (iduser2)
    REFERENCES User_ (iduser));


-- -----------------------------------------------------
-- Table Friend_Request
-- -----------------------------------------------------
CREATE TABLE Friend_Request (
  idrequest INTEGER GENERATED BY DEFAULT AS IDENTITY,
  iduser1 INT NOT NULL,
  iduser2 INT NOT NULL,
  PRIMARY KEY (idrequest),
  CONSTRAINT fk_Friend_Request_User1
    FOREIGN KEY (iduser1)
    REFERENCES User_ (iduser),
  CONSTRAINT fk_Friend_Request_User2
    FOREIGN KEY (iduser2)
    REFERENCES User_ (iduser));

INSERT INTO USER_(name,username,password,image) VALUES ('Diego Obin','DiiAns23','admin','');
INSERT INTO USER_(name,username,password,image) VALUES ('Jose Obin','YeNios','admin','');
INSERT INTO USER_(name,username,password,image) VALUES ('Juan Obin','JcMarro','admin','');
COMMIT;

INSERT INTO PUBLICATION(text,iduser,image) VALUES ('Nueva publicacion de prueba',1,'assets/public/WhatsApp Image 2021-04-25 at 8.42.19 PM (1).jpeg');
INSERT INTO PUBLICATION(text,iduser,image) VALUES ('Nueva publicacion de prueba numero 2',1,'assets/public/WhatsApp Image 2021-04-25 at 8.42.19 PM (1).jpeg');
INSERT INTO PUBLICATION(text,iduser,image) VALUES ('Nueva publicacion de prueba numero 3',1,'assets/public/WhatsApp Image 2021-04-25 at 8.42.19 PM (1).jpeg');

INSERT INTO PUBLICATION(text,iduser,image) VALUES ('Nueva publicacion de prueba numero 5',1,'assets/public/menor tres.PNG');




CREATE OR REPLACE PROCEDURE buscar_user(username_ in varchar, password_ in varchar) 
IS
existe number;
id_ number;
nombre_ varchar(20);
BEGIN
    existe:=0;
    SELECT Count(*) into existe 
    FROM User_
    WHERE username = username_ AND 
          password = password_;
    if existe = 0 then
        dbms_output.put_line('Este usuario no existe');
    else
        SELECT iduser INTO id_
        FROM User_
        WHERE username = username_ AND 
            password = password_;
        return id_;
        --dbms_output.put_line('Este usuario se llama: ' || id_);
    end if;
END;


BEGIN 
buscar_user('DiiAns23','admin');
COMMIT;
END;

CREATE OR REPLACE PROCEDURE insertar_user(name in varchar, username_ in varchar,
password in varchar, image in varchar)
IS
existe number;
BEGIN
    existe:=0;
    SELECT Count(*) into existe 
    FROM User_
    WHERE username = username_;
    
    if existe = 0 then
        insert into User_(name,username, password, image) values(name, username_, password, image);
        dbms_output.put_line('Usuario registrado con exito: ' || username_);
    else
        existe := -1;
        dbms_output.put_line('No registrado error: ' || existe);
    end if;
END;

BEGIN
    insertar_user('Diego Obin','Patron','admin','no-image');
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE retornar_user(username_ in varchar, password_ in varchar,
id_ out number, name_ out varchar)
AS
numero_ number;
BEGIN 
    SELECT iduser, name
    INTO id_, name_
    FROM User_
    WHERE 
        username = username_ and
        password = password_;
        dbms_output.put_line('Nombre: '||name_);
END retornar_user;

select status from all_objects where object_name = 'RETORNAR_USER';

DECLARE
    id_ user_.iduser%TYPE;
    nombre_ user_.name%TYPE;
BEGIN
    retornar_user('DiiAns23','hola',id_,nombre_);
END;





SELECT * FROM User_;


DROP TABLE Friend_Request;
DROP TABLE Message;
DROP TABLE Tags;
DROP TABLE Publication;
DROP TABLE Friend;
DROP TABLE User_;

COMMIT;







